build:
  environment:
    python: "3.10.8"
  dependencies:
    override:
      - "pip install -r requirements.txt -r requirements-test.txt"
  nodes:
    analysis:
      tests:
        override:
          - js-scrutinizer-run
          - py-scrutinizer-run
    coverage:
      environment:
        apt_packages:
          - language-pack-de
        variables:
          SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://scrutinizer:scrutinizer@127.0.0.1/scrutinizer"
      services:
        postgres: 15
      tests:
        override:
          - command: "pytest --cov=byceps tests"
            coverage:
              file: ".coverage"
              format: "py-cc"

filter:
  paths:
    - "byceps/"
  excluded_paths:
    - "byceps/static/behavior/vendor/"

tools:
  python_analyzer:
    config:
      duplication_detector:
        enabled: false
