x-byceps-base: &byceps-base
  build: .
  volumes:
    - .:/home/byceps
    - byceps-data:/home/byceps/data:rw
  depends_on:
    - db
    - redis
  environment:
    BYCEPS_CONFIG: /home/byceps/config/docker.toml
    REDIS_URL: "redis://redis/0"
    SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://byceps:byceps@db/byceps"

services:

  db:
    image: "postgres:15"
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: byceps
      POSTGRES_USER: byceps

  redis:
    image: "redis:7"

  byceps-admin:
    <<: *byceps-base
    environment:
      APP_MODE: admin

  byceps-site:
    <<: *byceps-base
    environment:
      APP_MODE: site
      SITE_ID: cozylan

  byceps-worker:
    <<: *byceps-base
    command: ./worker.py

  web:
    image: nginx
    volumes:
      - ./docker/nginx-templates:/etc/nginx/templates
      - .:/var/www/byceps
    depends_on:
      - byceps-admin
      - byceps-site
    ports:
      - "8081:81"
      - "8082:82"

volumes:
  byceps-data:
  db-data:
