services:

  db:
    image: "postgres:15"
    restart: always
    environment:
      POSTGRES_PASSWORD: byceps
      POSTGRES_USER: byceps

  redis:
    image: "redis:7"

  byceps-base:
    build: .
    volumes:
      - .:/home/byceps/app
      - ./data:/home/byceps/app/data:rw
    environment:
      BYCEPS_CONFIG: /home/byceps/app/config/docker.toml
      REDIS_URL: "redis://redis/0"
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://byceps:byceps@db/byceps"

  byceps-admin:
    extends: byceps-base
    depends_on:
      - db
      - redis
    environment:
      APP_MODE: admin

  byceps-site:
    extends: byceps-base
    depends_on:
      - db
      - redis
    environment:
      APP_MODE: site
      SITE_ID: cozylan

  byceps-worker:
    extends: byceps-base
    depends_on:
      - db
      - redis
    command: ./worker.py
