[build-system]
requires = [
    "setuptools >= 62.6.0",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 80
skip-string-normalization = true
target-version = [ "py39" ]

[tool.mypy]
python_version = "3.9"
plugins = "sqlalchemy.ext.mypy.plugin"
ignore_missing_imports = true
no_implicit_optional = true

[tool.pytest.ini_options]
addopts = "-vv -ra"
testpaths = [ "tests/unit", "tests/integration" ]

[tool.ruff]
ignore = [
    "E501",  # Line too long
]
