[[app_mounts]]
server_name = "byceps-admin.example"
mode = "admin"

[[app_mounts]]
server_name = "byceps-api.example"
mode = "api"

[[app_mounts]]
server_name = "cozylan.example"
mode = "site"
site_id = "cozylan"
