[[app_mounts]]
server_name = "admin.byceps.example"
mode = "admin"

[[app_mounts]]
server_name = "api.byceps.example"
mode = "api"

[[app_mounts]]
server_name = "cozylan.example"
mode = "site"
site_id = "cozylan"
