name: Docker Test

on:
  # Allow manual workflow triggering from the "Actions" tab.
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build containers
      run: docker-compose build

    - name: Generate secret key
      run: docker-compose run --rm byceps-admin byceps generate-secret-key

    - name: Initialize database
      run: docker-compose run --rm byceps-admin byceps initialize-database

    - name: Create demo data
      run: docker-compose run --rm byceps-admin byceps create-demo-data
